### ISSUE TITLE
Tensorboard traces are weird

### ISSUE THREAD

**Issue by iftenney** [jsalt18-sentence-repl/jiant#141]
Step counter seems to get reset & is non-unique, resulting in strange looking plots:
https://photos.app.goo.gl/sr818wGhEVSPhk8a9
https://photos.app.goo.gl/LjzKUq3VoYLtESsz8

**Comment by sleepinyourhat** [comment]
Still open? Is #402 relevant?

**Comment by Jan21** [comment]
Yes..This was resolved with #402..should be closed

**Comment by iftenney** [comment]
#402 addresses a similar bug (overlapping training traces when resuming a run), but not the issue with validation traces originally reported here.

(Also re-opening because #402 isn't ready to merge yet.)

**Comment by Jan21** [comment]
I'm convinced by #402....The step counter was not unique because the original code was not distinguishing between LC for pretraining and LC for target tasks....now we have separate channels for these.
