### ISSUE TITLE
Readme edge probing link is dead

### ISSUE THREAD

**Issue by Iwontbecreative** [jsalt18-sentence-repl/jiant#423]
> Edge probing analysis tasks: see probing/data for more information.

This links to a 404, mainly because there is no README on the repo. Not sure what the link should be/what info should be there so can't really propose a PR.

**Comment by pitrack** [comment]
There might be a more complete version somewhere; this is the most complete version I found (on another branch) https://github.com/jsalt18-sentence-repl/jiant/tree/edgeprobe_docs/probing/data

Even that version isn't complete (it's missing some things), so there might be a different branch with more.

**Comment by iftenney** [comment]
Sorry, as Patrick mentioned that file exists on a branch, but I haven't had a chance to go through everything on there and clean it up to merge yet.

**Comment by sleepinyourhat** [comment]
@iftenney - Fix or or close or unassign yourself?

**Comment by iftenney** [comment]
Working on it, will send a PR soon. (Sorry, tied up with a conference the past week.)

**Comment by iftenney** [comment]
See #430
