### ISSUE TITLE
Add the full CoLA task

### ISSUE THREAD

**Issue by sleepinyourhat** [jsalt18-sentence-repl/jiant#433]
Add a version of the CoLA the in-domain out-of-domain split described in the Warstadt paper.

**Comment by sleepinyourhat** [comment]
Where does this stand?

**Comment by summitcoworking** [comment]
It's on this branch - https://github.com/jsalt18-sentence-repl/jiant/tree/cola

**Comment by pruksmhc** [comment]
It's on this branch - https://github.com/jsalt18-sentence-repl/jiant/tree/cola

**Comment by sleepinyourhat** [comment]
Tx. I don't think that's a branch, though...

In any case, ready for a PR?

**Comment by pruksmhc** [comment]
Found a much simpler way to do the cola in and out domain -  https://github.com/jsalt18-sentence-repl/jiant/tree/cola_new

**Comment by sleepinyourhat** [comment]
Great! Ready for a PR soon?

**Comment by sleepinyourhat** [comment]
#502

**Comment by pruksmhc** [comment]
Addressed in https://github.com/jsalt18-sentence-repl/jiant/commit/31ead8f869fe253c78c6af64ca675c1c21379b7b
