### ISSUE TITLE
Incorporate PyTorch-BERT

### ISSUE THREAD

**Issue by sleepinyourhat** [jsalt18-sentence-repl/jiant#441]
https://twitter.com/Thom_Wolf/status/1073588652985466880

**Comment by iftenney** [comment]
I'll look in to this (most likely after the holidays) - would like to run edge probing on BERT. @W4ngatang , any others want to help out?

**Comment by iftenney** [comment]
Multi-GPU support would be very useful for BERT, since the models are huge.

**Comment by sleepinyourhat** [comment]
@Iwontbecreative @zphang Did you wind up getting far with this?

**Comment by sleepinyourhat** [comment]
There are now mentions of BERT in AllenNLP. Before we get too far, we should see what's already there.

Here's the issue, though it's not very helpful—I think something was committed without being mentioned here: https://github.com/allenai/allennlp/issues/1901

**Comment by sleepinyourhat** [comment]
It'd also be good to support BERT-style _unsupervised_ training, rather than just fine-tuning from pre-trained BERT weights. I'm not sure if HuggingFace or AllenNLP support that as-is.

**Comment by iftenney** [comment]
There's this: https://github.com/huggingface/pytorch-pretrained-BERT#2-bertforpretraining
But otherwise, they state that they don't intend to support this until PyTorch supports TPUs: https://github.com/huggingface/pytorch-pretrained-BERT#tpu

**Comment by sleepinyourhat** [comment]
Safe to close this?
