### ISSUE TITLE
How to evaluate my own sentence encoder (SentEval style)

### ISSUE THREAD

**Issue by chledowski** [jsalt18-sentence-repl/jiant#457]
Hi,

I am trying to reproduce results from GLUE using sentence embeddings (GenSen, InferSent, ..).

Please correct me if I'm wrong: such evaluation should train a different classifier for each task, and the sentence embeddings should be fixed?

I have trained some sentence embedding on my data and am wondering if there is an straightforward way to evaluate such encoders instead of rnn/transformer/bow.

**Comment by W4ngatang** [comment]
Hey, thanks for the interest. You're right in that for our baseline experiments, we trained an encoder, then trained a classifier per GLUE-task on top of the frozen encoder, but you are certainly allowed to fine-tune the sentence encoder instead. For the fixed-dimensional sentence encoders, I actually used SentEval; I have a version that adds the GLUE tasks that I plan adding as a PR to their repo soon.

**Comment by chledowski** [comment]
Thanks for your quick response.

That's great news. Could you give a rough estimate on when are you planning to add the PR? Sorry for bringing this up again, I'm trying to estimate if I should do it myself or wait for the PR :)

**Comment by chledowski** [comment]
If you don't mind, I could help with the PR if there is something else to do.

**Comment by arianhosseini** [comment]
Hi @chledowski,
Could you point me to your implementation of GLUE in SentEval style if it's public?

Thanks a lot.

**Comment by chledowski** [comment]
Hi @arianhosseini, here's the repo: https://github.com/applicaai/senteval

Please remember, that its not a final version yet - among others, I need to add F1 score computation for QQP, computation of macro average and generation of files that could be submitted to GLUE leaderboard.

**Comment by W4ngatang** [comment]
I've been using this: https://github.com/W4ngatang/SentEval
I haven't touched it in a bit, but the usage should be similar if not identical to using SentEval.
I'll be using this again in the next few days, so feel free to ask questions.
Hope it helps!

**Comment by chledowski** [comment]
Hi @W4ngatang, thank you so much for sharing the code with me!

I am trying to use it to get more similar results to the ones you have reported. What I had to do, is to convert the code from python2 to python3, and fix some other issues. Tomorrow, I think I'll finish doing that (I will share the code if you're interested).

I have a question: what is `sst_binary_test_ans.tsv` file in `SST2` evaluation? It is not present in glue datasets. Also, there is no `multinli_1.0_dev_both.txt`, but I figured it must be the concat of matched and mismatched :)

**Comment by chledowski** [comment]
Hi, 

I have figured out that this is the same dataset, but with indexes. 

We have noticed, that the results have quite a big variance on smaller datasetes like RTE, QNLI, CoLA, where the results differ by ~5% between two seeds. Maybe more epochs should be used for the evaluation.

I have also noticed, that in the examples, there are different default parameters for gensen and infersent vectorizers (im talking about epoch_size, optimizer, etc) - I am wondering, if these are the parameters you have used for evaluation?

**Comment by W4ngatang** [comment]
Hey @chledowski ,

First, can we move discussion of this over to the SentEval fork? This isn't really relevant to jiant.

It's not unusual to have higher variance for the smaller datasets (though QNLI is decently large). I think did use the defaults in the code.
