### ISSUE TITLE
'null' not identified as valid sentence encoder specification

### ISSUE THREAD

**Issue by xiaoyizy** [jsalt18-sentence-repl/jiant#541]
Hi,

Setting `sent_enc = null` in conf script caused error "No valid sentence encoder specified" from line 135 of `models.py`. Further tests showed that `args.sent_enc == "null"` returned `False` under `build_sent_encoder`. 

After changing `"null"` to `"none"` in `build_sent_encoder` else/if conditions, the code was functional.

**Comment by pruksmhc** [comment]
We currently use HOCON for the config language. You probably want to try sent_enc = "null"  (with quotation marks).

**Comment by xiaoyizy** [comment]
Thanks for your advice! However quotation mark had no effect on this issue. Running `print(args.sent_enc)` and `args.sent_enc == 'null'` returned `'null'` and `False`.

**Comment by HaokunLiu** [comment]
Ha! I have done this before. It should be double quotation mark. "null", not 'null'.

**Comment by sleepinyourhat** [comment]
Should be fixed! Changed the expected keyword from 'null' to 'none' to avoid some tricky HOCON escaping issues.
